### ISSUE TITLE
Can you chance the Design of the Icons for 1.12.2

### ISSUE THREAD

**Issue by Titoo8899** [MBYL-InkAndSoul/GamemodeSwitcher#1]
hi,
can you make in the next version of your GamemodeSwitcher Mod the Icons more realistic to the Original with a better size of the Original Iconsize of Minecraft

**Comment by Titoo8899** [comment]
Okay I have found a video to this what help.

**Comment by MBYL-InkAndSoul** [comment]
I can try to improve the icons in next version. (Now icons from NEI because I'm lazy and this mod was originally made for myself...)

But, Idk how to scale down and keep the full rendering. 😐

I tried it. Smaller scale will cut image (The corner will be missing).

Sorry, I'm just a noob modder. I don't know how to fix it.

**Comment by MBYL-InkAndSoul** [comment]
Ok, I copy a piece of modern Minecraft and remap to fix it.

So, I will not upload the source of new version.

**Comment by Titoo8899** [comment]
Thank you, it works fine and looks very good and the Config is easy
